export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";


//FOR SINGLE POST WITH COMMENTS

export const FETCH_SINGLE_POST_REQUEST = "FETCH_SINGLE_POST_REQUEST";
export const FETCH_SINGLE_POST_SUCCESS = "FETCH_SINGLE_POST_SUCCESS";
export const FETCH_SINGLE_POST_ERROR = "FETCH_SINGLE_POST_FAILURE";



//FOR CREATING POST
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_FAILURE";


//RESET MESSAGE AND ERROR
export const RESET_MESSAGE = "RESET_MESSAGE";
export const RESET_ERROR = "RESET_ERROR";

//UPDATE POST
export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_ERROR = "UPDATE_POST_ERROR";



//DELETE POST
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";


//COMMENT
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";
export const DELETE_COMMENT = "DELETE_COMMENT";



